root = "D:/code/DEMOS/"
icon_path = root + "po-ico.png"   # .png or .ico both work
exe_name  = "Pixelove Ole"   # -> dist/<exe_name>.exe
excluded_dirs = (root + "demos/demo1", root + "demos/demo3", root + "demos/pc45", root + "demos/petscii")

"""
One-shot build script for the DEMOS launcher.

    python build-exe.py

Produces a self-contained one-file  dist/<exe_name>.exe  with every fix we need:

  * collects arcade / pyglet / pymunk / pytiled_parser / sounddevice data files,
    native libs (chipmunk, PortAudio) and metadata  -> fixes the original
    "Unable to load version number via ...arcade\\VERSION" crash;
  * drops the bad 'arcade/VERSION/VERSION' entry that arcade's own PyInstaller
    hook creates (it declares the VERSION *file*'s destination as a *directory*),
    which otherwise aborts one-file extraction with
    "Failed to extract arcade\\VERSION\\VERSION";
  * bundles the whole demos/ and lib/ asset trees and installs a runtime hook
    that chdir()s into the extraction dir, so both the CWD-relative loads
    ("demos/.../resources/...", os.getcwd()+...) and the __file__-relative ones
    (pc45 / petscii fonts, petscii sounds) resolve to the bundled copies;
  * converts the icon to a multi-size .ico and embeds it.

Edit the two settings on the first lines above. Run the built exe DIRECTLY
(double-click or  dist\\pc45years.exe demo3 w) -- never via  python <exe>.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


# --- runtime hook written next to this script -------------------------------
RT_HOOK = """# PyInstaller runtime hook (generated by build-exe.py).
# Switch CWD to the one-file extraction dir (sys._MEIPASS) so the demos'
# CWD-relative asset loads resolve to the bundled copies. __file__-relative
# lookups already point inside the same dir, so every style then agrees.
import os
import sys

if getattr(sys, "frozen", False):
    _meipass = getattr(sys, "_MEIPASS", None)
    if _meipass:
        try:
            os.chdir(_meipass)
        except OSError:
            pass
"""


# --- the .spec written next to this script (@@...@@ filled in below) ---------
SPEC_TEMPLATE = """# -*- mode: python ; coding: utf-8 -*-
# AUTO-GENERATED by build-exe.py -- do not edit by hand; re-run build-exe.py.
import os
import sys
from PyInstaller.utils.hooks import collect_all, collect_submodules, copy_metadata

PROJECT_DIR = @@PROJECT@@
ICON = @@ICON@@
EXE_NAME = @@NAME@@
EXCLUDED_DIRS = @@EXCLUDED@@

# normalize once so os.walk pruning can compare case-/separator-insensitively
_EXCLUDED = tuple(os.path.normcase(os.path.normpath(p)) for p in EXCLUDED_DIRS)

datas = []
binaries = []
hiddenimports = []


def _collect(pkg):
    global datas, binaries, hiddenimports
    try:
        d, b, h = collect_all(pkg)
    except Exception as exc:
        print("[spec] collect_all(%r) skipped: %s" % (pkg, exc))
        return
    datas += d
    binaries += b
    hiddenimports += h


# arcade & friends ship data files / native libs / lazily-imported submodules
for _pkg in ("arcade", "pyglet", "pymunk", "pytiled_parser", "sounddevice",
             "OpenGL", "OpenGL_accelerate"):
    _collect(_pkg)

# PyOpenGL selects its platform / array backends dynamically at import time;
# collect_all above bundles the package + native libs, this adds the lazily
# imported submodules. Fail loudly if the build interpreter can't see PyOpenGL,
# rather than silently shipping an exe that crashes with "No module named 'OpenGL'".
_gl = collect_submodules("OpenGL")
if not _gl:
    raise SystemExit(
        "[spec] PyOpenGL not importable by the build interpreter (%s). "
        "Install it here: python -m pip install PyOpenGL PyOpenGL_accelerate" % sys.executable)
hiddenimports += _gl

# runtime importlib.metadata.version(...) lookups
for _pkg in ("arcade", "pyglet", "pymunk", "pillow"):
    try:
        datas += copy_metadata(_pkg)
    except Exception as exc:
        print("[spec] copy_metadata(%r) skipped: %s" % (_pkg, exc))


# the demos load their own assets by CWD-relative and __file__-relative paths;
# bundle the whole trees so both styles resolve inside the extraction dir
def _is_excluded(path):
    norm = os.path.normcase(os.path.normpath(path))
    return any(norm == ex or norm.startswith(ex + os.sep) for ex in _EXCLUDED)


def _add_tree(top):
    out = []
    base = os.path.join(PROJECT_DIR, top)
    for root, dirs, files in os.walk(base):
        # prune __pycache__ and any excluded dir (with all its sub-dirs)
        dirs[:] = [d for d in dirs
                   if d != "__pycache__" and not _is_excluded(os.path.join(root, d))]
        if _is_excluded(root):
            continue
        for name in files:
            if name.endswith((".pyc", ".pyo")):
                continue
            out.append((os.path.join(root, name), os.path.relpath(root, PROJECT_DIR)))
    return out


for _tree in ("demos", "lib"):
    datas += _add_tree(_tree)


a = Analysis(
    [os.path.join(PROJECT_DIR, "main.py")],
    pathex=[PROJECT_DIR],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[os.path.join(PROJECT_DIR, "rt_hook_chdir.py")],
    excludes=[],
    noarchive=False,
    optimize=0,
)

# arcade's shipped hook mis-files VERSION into a DIRECTORY 'arcade/VERSION/',
# colliding with the real 'arcade/VERSION' file and breaking one-file extraction
# ("Failed to extract arcade/VERSION/VERSION"). Drop the mis-placed nested entry
# while keeping the real file whose dest is exactly 'arcade/VERSION'.
_bad = os.path.normpath(os.path.join("arcade", "VERSION")) + os.sep
a.datas = [d for d in a.datas if not os.path.normpath(d[0]).startswith(_bad)]

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name=EXE_NAME,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=ICON,
)
"""


def _ensure_ico(src):
    """Return a path to a .ico for `src` (used as-is if already .ico, else converted)."""
    if not src:
        return None
    src = os.path.abspath(src)
    if not os.path.isfile(src):
        sys.exit("icon_path not found: %s" % src)
    if src.lower().endswith(".ico"):
        return src
    try:
        from PIL import Image
    except ImportError:
        sys.exit("Pillow is needed to convert %s to .ico  (pip install pillow)" % src)
    ico = os.path.join(HERE, "app.ico")
    Image.open(src).convert("RGBA").save(
        ico, format="ICO",
        sizes=[(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)])
    print("[build-exe] icon: %s -> app.ico" % os.path.basename(src))
    return ico


def render_spec(project, ico, name, excluded):
    icon_repr = repr(ico) if ico else "None"
    return (SPEC_TEMPLATE
            .replace("@@PROJECT@@", repr(project))
            .replace("@@ICON@@", icon_repr)
            .replace("@@NAME@@", repr(name))
            .replace("@@EXCLUDED@@", repr(tuple(excluded))))


def write_build_files(ico):
    with open(os.path.join(HERE, "rt_hook_chdir.py"), "w", encoding="utf-8") as f:
        f.write(RT_HOOK)
    spec = os.path.join(HERE, "main.spec")
    with open(spec, "w", encoding="utf-8") as f:
        f.write(render_spec(HERE, ico, exe_name, excluded_dirs))
    return spec


def main():
    if not os.path.isfile(os.path.join(HERE, "main.py")):
        sys.exit("main.py must sit next to build-exe.py (looked in %s)" % HERE)

    ico = _ensure_ico(icon_path)
    spec = write_build_files(ico)

    try:
        import PyInstaller.__main__ as pyi
    except ImportError:
        sys.exit("PyInstaller is not installed for this Python. Run: pip install pyinstaller")

    dist = os.path.join(HERE, "dist")
    work = os.path.join(HERE, "build")
    print("[build-exe] building %s.exe (a few minutes)..." % exe_name)
    pyi.run([spec, "--noconfirm", "--distpath", dist, "--workpath", work])

    out = os.path.join(dist, exe_name + ".exe")
    if not os.path.isfile(out):
        sys.exit("[build-exe] build finished but %s was not produced" % out)
    print("[build-exe] SUCCESS -> %s" % out)
    print("[build-exe] run it DIRECTLY (never 'python %s.exe'):" % exe_name)
    print("            %s demo3 w" % out)


if __name__ == "__main__":
    main()
