root = "D:/code/DEMOS/"
icon_path = root + "icons/" + "p3dscii-ico.png"   # .png or .ico both work
exe_name  = "P3DSCII - PETSCII 3D DEMO"   # -> dist/<exe_name>.exe
excluded_dirs = (root + "demos/demo1", root + "demos/demo3", root + "demos/pc45")

# Text baked onto the boot splash that shows IMMEDIATELY while the one-file exe
# unpacks itself to a temp dir (the multi-second "nothing happens" gap on start).
# Edit these two lines and re-run this script to change the message.
splash_line1 = "Please be patient . . . . ."
splash_line2 = "DECRUNCHING"

# Boot splash IMAGE. Point this at your own picture to use a CUSTOM splash --
# an opaque PNG, sized how you want it to appear on screen (GIF/BMP also work).
# If the file is missing, one is auto-generated from the two lines above.
# Set to None to always auto-generate and never look for a custom image.
splash_image = root + "screens/splash.png"

"""
One-shot build script for the DEMOS launcher.

    python build-exe.py

Produces a self-contained one-file  dist/<exe_name>.exe  with every fix we need:

  * collects arcade / pyglet / pymunk / pytiled_parser / sounddevice data files,
    native libs (chipmunk, PortAudio) and metadata  -> fixes the original
    "Unable to load version number via ...arcade\\VERSION" crash;
  * drops the bad 'arcade/VERSION/VERSION' entry that arcade's own PyInstaller
    hook creates (it declares the VERSION *file*'s destination as a *directory*),
    which otherwise aborts one-file extraction with
    "Failed to extract arcade\\VERSION\\VERSION";
  * bundles the whole demos/ and lib/ asset trees and installs a runtime hook
    that chdir()s into the extraction dir, so both the CWD-relative loads
    ("demos/.../resources/...", os.getcwd()+...) and the __file__-relative ones
    (pc45 / petscii fonts, petscii sounds) resolve to the bundled copies;
  * converts the icon to a multi-size .ico and embeds it.

Edit the two settings on the first lines above. Run the built exe DIRECTLY
(double-click or  dist\\pc45years.exe demo3 w) -- never via  python <exe>.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


# --- runtime hook written next to this script -------------------------------
RT_HOOK = """# PyInstaller runtime hook (generated by build-exe.py).
# Switch CWD to the one-file extraction dir (sys._MEIPASS) so the demos'
# CWD-relative asset loads resolve to the bundled copies. __file__-relative
# lookups already point inside the same dir, so every style then agrees.
import os
import sys

if getattr(sys, "frozen", False):
    _meipass = getattr(sys, "_MEIPASS", None)
    if _meipass:
        try:
            os.chdir(_meipass)
        except OSError:
            pass
"""


# --- the .spec written next to this script (@@...@@ filled in below) ---------
SPEC_TEMPLATE = """# -*- mode: python ; coding: utf-8 -*-
# AUTO-GENERATED by build-exe.py -- do not edit by hand; re-run build-exe.py.
import os
import sys
from PyInstaller.utils.hooks import collect_all, collect_submodules, copy_metadata

PROJECT_DIR = @@PROJECT@@
ICON = @@ICON@@
EXE_NAME = @@NAME@@
EXCLUDED_DIRS = @@EXCLUDED@@
SPLASH_IMAGE = @@SPLASH@@

# normalize once so os.walk pruning can compare case-/separator-insensitively
_EXCLUDED = tuple(os.path.normcase(os.path.normpath(p)) for p in EXCLUDED_DIRS)

datas = []
binaries = []
hiddenimports = []


def _collect(pkg):
    global datas, binaries, hiddenimports
    try:
        d, b, h = collect_all(pkg)
    except Exception as exc:
        print("[spec] collect_all(%r) skipped: %s" % (pkg, exc))
        return
    datas += d
    binaries += b
    hiddenimports += h


# arcade & friends ship data files / native libs / lazily-imported submodules
for _pkg in ("arcade", "pyglet", "pymunk", "pytiled_parser", "sounddevice",
             "OpenGL", "OpenGL_accelerate"):
    _collect(_pkg)

# PyOpenGL selects its platform / array backends dynamically at import time;
# collect_all above bundles the package + native libs, this adds the lazily
# imported submodules. Fail loudly if the build interpreter can't see PyOpenGL,
# rather than silently shipping an exe that crashes with "No module named 'OpenGL'".
_gl = collect_submodules("OpenGL")
if not _gl:
    raise SystemExit(
        "[spec] PyOpenGL not importable by the build interpreter (%s). "
        "Install it here: python -m pip install PyOpenGL PyOpenGL_accelerate" % sys.executable)
hiddenimports += _gl

# runtime importlib.metadata.version(...) lookups
for _pkg in ("arcade", "pyglet", "pymunk", "pillow"):
    try:
        datas += copy_metadata(_pkg)
    except Exception as exc:
        print("[spec] copy_metadata(%r) skipped: %s" % (_pkg, exc))


# the demos load their own assets by CWD-relative and __file__-relative paths;
# bundle the whole trees so both styles resolve inside the extraction dir
def _is_excluded(path):
    norm = os.path.normcase(os.path.normpath(path))
    return any(norm == ex or norm.startswith(ex + os.sep) for ex in _EXCLUDED)


def _add_tree(top):
    out = []
    base = os.path.join(PROJECT_DIR, top)
    for root, dirs, files in os.walk(base):
        # prune __pycache__ and any excluded dir (with all its sub-dirs)
        dirs[:] = [d for d in dirs
                   if d != "__pycache__" and not _is_excluded(os.path.join(root, d))]
        if _is_excluded(root):
            continue
        for name in files:
            if name.endswith((".pyc", ".pyo")):
                continue
            out.append((os.path.join(root, name), os.path.relpath(root, PROJECT_DIR)))
    return out


for _tree in ("demos", "lib"):
    datas += _add_tree(_tree)


a = Analysis(
    [os.path.join(PROJECT_DIR, "main.py")],
    pathex=[PROJECT_DIR],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[os.path.join(PROJECT_DIR, "rt_hook_chdir.py")],
    excludes=[],
    noarchive=False,
    optimize=0,
)

# arcade's shipped hook mis-files VERSION into a DIRECTORY 'arcade/VERSION/',
# colliding with the real 'arcade/VERSION' file and breaking one-file extraction
# ("Failed to extract arcade/VERSION/VERSION"). Drop the mis-placed nested entry
# while keeping the real file whose dest is exactly 'arcade/VERSION'.
_bad = os.path.normpath(os.path.join("arcade", "VERSION")) + os.sep
a.datas = [d for d in a.datas if not os.path.normpath(d[0]).startswith(_bad)]

pyz = PYZ(a.pure)

# --- boot splash: shown by the C bootloader DURING one-file extraction --------
# The one-file exe must unpack ~0.5 GB to a temp dir before Python even starts;
# that is the multi-second "nothing happens" gap on launch. The splash's tiny Tk
# deps are unpacked FIRST, so the "DECRUNCHING" image appears almost immediately
# and stays up through the rest of extraction + the heavy arcade/pyglet imports.
# main.py calls pyi_splash.close() once it is about to open the demo window.
splash = None
if SPLASH_IMAGE and os.path.isfile(SPLASH_IMAGE):
    try:
        splash = Splash(
            SPLASH_IMAGE,
            binaries=a.binaries,
            datas=a.datas,
            always_on_top=True,
        )
    except Exception as exc:
        print("[spec] splash disabled: %s" % exc)
        splash = None
else:
    print("[spec] no splash image at %r -- building without splash" % (SPLASH_IMAGE,))

# in one-file mode both the splash target and its binaries belong in EXE
_splash_args = [splash, splash.binaries] if splash is not None else []

exe = EXE(
    pyz,
    a.scripts,
    *_splash_args,
    a.binaries,
    a.datas,
    [],
    name=EXE_NAME,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    # keep UPX away from the splash's Tk runtime -- UPX can corrupt these DLLs
    # and the splash then silently fails to show
    upx_exclude=["vcruntime140.dll", "tcl86t.dll", "tk86t.dll",
                 "tcl86.dll", "tk86.dll"],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=ICON,
)
"""


def _ensure_ico(src):
    """Return a path to a .ico for `src` (used as-is if already .ico, else converted)."""
    if not src:
        return None
    src = os.path.abspath(src)
    if not os.path.isfile(src):
        sys.exit("icon_path not found: %s" % src)
    if src.lower().endswith(".ico"):
        return src
    try:
        from PIL import Image
    except ImportError:
        sys.exit("Pillow is needed to convert %s to .ico  (pip install pillow)" % src)
    ico = os.path.join(HERE, "icons/app.ico")
    Image.open(src).convert("RGBA").save(
        ico, format="ICO",
        sizes=[(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)])
    print("[build-exe] icon: %s -> app.ico" % os.path.basename(src))
    return ico


def _ensure_splash():
    """Generate screens/splash_po.png -- the image the bootloader shows during one-file
    extraction. Returns its path, or None (the build then proceeds with no splash)."""
    try:
        from PIL import Image, ImageDraw, ImageFont
    except ImportError:
        print("[build-exe] Pillow missing -- building without splash screen")
        return None

    W, H = 560, 300
    bg, border = (10, 12, 22), (0, 200, 180)
    title_c, line1_c, crunch_c, foot_c = (
        (232, 232, 244), (200, 200, 214), (120, 255, 140), (110, 110, 130))

    fonts_dir = os.path.join(os.environ.get("WINDIR", r"C:\Windows"), "Fonts")

    def font(px, bold=False):
        names = (["impact.ttf", "arialbd.ttf", "segoeuib.ttf"] if bold
                 else ["arial.ttf", "segoeui.ttf"])
        for name in names:
            for cand in (os.path.join(fonts_dir, name), name):
                try:
                    return ImageFont.truetype(cand, px)
                except OSError:
                    continue
        return ImageFont.load_default()

    img = Image.new("RGB", (W, H), bg)
    d = ImageDraw.Draw(img)
    d.rectangle([6, 6, W - 7, H - 7], outline=border, width=2)

    def centered(text, y, fnt, fill):
        left, _, right, _ = d.textbbox((0, 0), text, font=fnt)
        d.text(((W - (right - left)) / 2 - left, y), text, font=fnt, fill=fill)

    centered(exe_name.upper(), 42, font(46, bold=True), title_c)
    centered(splash_line1, 150, font(24), line1_c)
    centered(splash_line2, 184, font(52, bold=True), crunch_c)
    centered("unpacking bundled data - first launch is the slow one",
             H - 44, font(15), foot_c)

    out = os.path.join(HERE, "screens", "splash_po.png")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    try:
        img.save(out, format="PNG")
    except OSError as exc:
        print("[build-exe] could not write splash image: %s" % exc)
        return None
    print("[build-exe] splash: %s -> splash_po.png" % (splash_line2,))
    return out


def render_spec(project, ico, name, excluded, splash):
    icon_repr = repr(ico) if ico else "None"
    splash_repr = repr(splash) if splash else "None"
    return (SPEC_TEMPLATE
            .replace("@@PROJECT@@", repr(project))
            .replace("@@ICON@@", icon_repr)
            .replace("@@NAME@@", repr(name))
            .replace("@@EXCLUDED@@", repr(tuple(excluded)))
            .replace("@@SPLASH@@", splash_repr))


def write_build_files(ico, splash):
    with open(os.path.join(HERE, "rt_hook_chdir.py"), "w", encoding="utf-8") as f:
        f.write(RT_HOOK)
    spec = os.path.join(HERE, "main.spec")
    with open(spec, "w", encoding="utf-8") as f:
        f.write(render_spec(HERE, ico, exe_name, excluded_dirs, splash))
    return spec


def _resolve_splash():
    """Pick the splash image to bake in: the custom `splash_image` if that file
    exists, otherwise an auto-generated one. Generation is never removed -- it is
    the fallback. Returns a path, or None to build with no splash."""
    if splash_image:
        custom = os.path.abspath(splash_image)
        if os.path.isfile(custom):
            print("[build-exe] splash: custom image %s" % custom)
            return custom
        print("[build-exe] no custom splash at %s -- generating one instead" % custom)
    return _ensure_splash()


def main():
    if not os.path.isfile(os.path.join(HERE, "main.py")):
        sys.exit("main.py must sit next to build-exe.py (looked in %s)" % HERE)

    ico = _ensure_ico(icon_path)
    splash = _resolve_splash()
    spec = write_build_files(ico, splash)

    try:
        import PyInstaller.__main__ as pyi
    except ImportError:
        sys.exit("PyInstaller is not installed for this Python. Run: pip install pyinstaller")

    dist = os.path.join(HERE, "dist")
    work = os.path.join(HERE, "build")
    print("[build-exe] building %s.exe (a few minutes)..." % exe_name)
    pyi.run([spec, "--noconfirm", "--distpath", dist, "--workpath", work])

    out = os.path.join(dist, exe_name + ".exe")
    if not os.path.isfile(out):
        sys.exit("[build-exe] build finished but %s was not produced" % out)
    print("[build-exe] SUCCESS -> %s" % out)
    print("[build-exe] run it DIRECTLY (never 'python %s.exe'):" % exe_name)
    print("            %s demo3 w" % out)


if __name__ == "__main__":
    main()
