# -*- mode: python ; coding: utf-8 -*-
# AUTO-GENERATED by build-exe.py -- do not edit by hand; re-run build-exe.py.
import os
import sys
from PyInstaller.utils.hooks import collect_all, collect_submodules, copy_metadata

PROJECT_DIR = 'D:\\code\\DEMOS'
ICON = 'D:\\code\\DEMOS\\icons/app.ico'
EXE_NAME = 'P3DSCII - PETSCII 3D DEMO'
EXCLUDED_DIRS = ('D:/code/DEMOS/demos/demo1', 'D:/code/DEMOS/demos/demo3', 'D:/code/DEMOS/demos/pc45')
SPLASH_IMAGE = 'D:\\code\\DEMOS\\screens\\splash_p3dscii.png'

# normalize once so os.walk pruning can compare case-/separator-insensitively
_EXCLUDED = tuple(os.path.normcase(os.path.normpath(p)) for p in EXCLUDED_DIRS)

datas = []
binaries = []
hiddenimports = []


def _collect(pkg):
    global datas, binaries, hiddenimports
    try:
        d, b, h = collect_all(pkg)
    except Exception as exc:
        print("[spec] collect_all(%r) skipped: %s" % (pkg, exc))
        return
    datas += d
    binaries += b
    hiddenimports += h


# arcade & friends ship data files / native libs / lazily-imported submodules
for _pkg in ("arcade", "pyglet", "pytiled_parser", "sounddevice",
             "OpenGL", "OpenGL_accelerate"):
    _collect(_pkg)

# PyOpenGL selects its platform / array backends dynamically at import time;
# collect_all above bundles the package + native libs, this adds the lazily
# imported submodules. Fail loudly if the build interpreter can't see PyOpenGL,
# rather than silently shipping an exe that crashes with "No module named 'OpenGL'".
_gl = collect_submodules("OpenGL")
if not _gl:
    raise SystemExit(
        "[spec] PyOpenGL not importable by the build interpreter (%s). "
        "Install it here: python -m pip install PyOpenGL PyOpenGL_accelerate" % sys.executable)
hiddenimports += _gl

# runtime importlib.metadata.version(...) lookups
for _pkg in ("arcade", "pyglet", "pillow"):
    try:
        datas += copy_metadata(_pkg)
    except Exception as exc:
        print("[spec] copy_metadata(%r) skipped: %s" % (_pkg, exc))


# the demos load their own assets by CWD-relative and __file__-relative paths;
# bundle the whole trees so both styles resolve inside the extraction dir
def _is_excluded(path):
    norm = os.path.normcase(os.path.normpath(path))
    return any(norm == ex or norm.startswith(ex + os.sep) for ex in _EXCLUDED)


def _add_tree(top):
    out = []
    base = os.path.join(PROJECT_DIR, top)
    for root, dirs, files in os.walk(base):
        # prune __pycache__ and any excluded dir (with all its sub-dirs)
        dirs[:] = [d for d in dirs
                   if d != "__pycache__" and not _is_excluded(os.path.join(root, d))]
        if _is_excluded(root):
            continue
        for name in files:
            if name.endswith((".pyc", ".pyo")):
                continue
            out.append((os.path.join(root, name), os.path.relpath(root, PROJECT_DIR)))
    return out


for _tree in ("demos", "lib"):
    datas += _add_tree(_tree)


a = Analysis(
    [os.path.join(PROJECT_DIR, "main.py")],
    pathex=[PROJECT_DIR],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[os.path.join(PROJECT_DIR, "rt_hook_chdir.py")],
    excludes=[],
    noarchive=False,
    optimize=0,
)

# arcade's shipped hook mis-files VERSION into a DIRECTORY 'arcade/VERSION/',
# colliding with the real 'arcade/VERSION' file and breaking one-file extraction
# ("Failed to extract arcade/VERSION/VERSION"). Drop the mis-placed nested entry
# while keeping the real file whose dest is exactly 'arcade/VERSION'.
_bad = os.path.normpath(os.path.join("arcade", "VERSION")) + os.sep
a.datas = [d for d in a.datas if not os.path.normpath(d[0]).startswith(_bad)]

pyz = PYZ(a.pure)

# --- boot splash: shown by the C bootloader DURING one-file extraction --------
# The one-file exe must unpack ~0.5 GB to a temp dir before Python even starts;
# that is the multi-second "nothing happens" gap on launch. The splash's tiny Tk
# deps are unpacked FIRST, so the "DECRUNCHING" image appears almost immediately
# and stays up through the rest of extraction + the heavy arcade/pyglet imports.
# main.py calls pyi_splash.close() once it is about to open the demo window.
splash = None
if SPLASH_IMAGE and os.path.isfile(SPLASH_IMAGE):
    try:
        splash = Splash(
            SPLASH_IMAGE,
            binaries=a.binaries,
            datas=a.datas,
            always_on_top=True,
        )
    except Exception as exc:
        print("[spec] splash disabled: %s" % exc)
        splash = None
else:
    print("[spec] no splash image at %r -- building without splash" % (SPLASH_IMAGE,))

# in one-file mode both the splash target and its binaries belong in EXE
_splash_args = [splash, splash.binaries] if splash is not None else []

exe = EXE(
    pyz,
    a.scripts,
    *_splash_args,
    a.binaries,
    a.datas,
    [],
    name=EXE_NAME,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    # keep UPX away from the splash's Tk runtime -- UPX can corrupt these DLLs
    # and the splash then silently fails to show
    upx_exclude=["vcruntime140.dll", "tcl86t.dll", "tk86t.dll",
                 "tcl86.dll", "tk86.dll"],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=ICON,
)
