# PyInstaller runtime hook (generated by build-exe.py).
# Switch CWD to the one-file extraction dir (sys._MEIPASS) so the demos'
# CWD-relative asset loads resolve to the bundled copies. __file__-relative
# lookups already point inside the same dir, so every style then agrees.
import os
import sys

if getattr(sys, "frozen", False):
    _meipass = getattr(sys, "_MEIPASS", None)
    if _meipass:
        try:
            os.chdir(_meipass)
        except OSError:
            pass
